/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CalendarEvent {
  'id' : string,
  'startTime' : bigint,
  'title' : string,
  'endTime' : bigint,
  'description' : string,
  'location' : string,
}
export interface Email {
  'id' : string,
  'subject' : string,
  'isStarred' : boolean,
  'body' : string,
  'isRead' : boolean,
  'timestamp' : bigint,
  'senderName' : string,
  'category' : string,
  'senderEmail' : string,
}
export interface Task {
  'id' : string,
  'title' : string,
  'isCompleted' : boolean,
  'dueDate' : bigint,
  'priority' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createEvent' : ActorMethod<
    [string, string, bigint, bigint, string],
    CalendarEvent
  >,
  'createTask' : ActorMethod<[string, bigint, string], Task>,
  'deleteEvent' : ActorMethod<[string], undefined>,
  'deleteTask' : ActorMethod<[string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEmailById' : ActorMethod<[string], [] | [Email]>,
  'getEmails' : ActorMethod<[], Array<Email>>,
  'getEvents' : ActorMethod<[], Array<CalendarEvent>>,
  'getTasks' : ActorMethod<[], Array<Task>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initDemoData' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markEmailRead' : ActorMethod<[string], undefined>,
  'rewriteBody' : ActorMethod<[string, string], string>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'summarizeEmail' : ActorMethod<[string], string>,
  'toggleStarEmail' : ActorMethod<[string], undefined>,
  'toggleTask' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];