/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CalendarEvent = IDL.Record({
  'id' : IDL.Text,
  'startTime' : IDL.Int,
  'title' : IDL.Text,
  'endTime' : IDL.Int,
  'description' : IDL.Text,
  'location' : IDL.Text,
});
export const Task = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'isCompleted' : IDL.Bool,
  'dueDate' : IDL.Int,
  'priority' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Email = IDL.Record({
  'id' : IDL.Text,
  'subject' : IDL.Text,
  'isStarred' : IDL.Bool,
  'body' : IDL.Text,
  'isRead' : IDL.Bool,
  'timestamp' : IDL.Int,
  'senderName' : IDL.Text,
  'category' : IDL.Text,
  'senderEmail' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createEvent' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Int, IDL.Int, IDL.Text],
      [CalendarEvent],
      [],
    ),
  'createTask' : IDL.Func([IDL.Text, IDL.Int, IDL.Text], [Task], []),
  'deleteEvent' : IDL.Func([IDL.Text], [], []),
  'deleteTask' : IDL.Func([IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEmailById' : IDL.Func([IDL.Text], [IDL.Opt(Email)], ['query']),
  'getEmails' : IDL.Func([], [IDL.Vec(Email)], ['query']),
  'getEvents' : IDL.Func([], [IDL.Vec(CalendarEvent)], ['query']),
  'getTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initDemoData' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markEmailRead' : IDL.Func([IDL.Text], [], []),
  'rewriteBody' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'summarizeEmail' : IDL.Func([IDL.Text], [IDL.Text], []),
  'toggleStarEmail' : IDL.Func([IDL.Text], [], []),
  'toggleTask' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CalendarEvent = IDL.Record({
    'id' : IDL.Text,
    'startTime' : IDL.Int,
    'title' : IDL.Text,
    'endTime' : IDL.Int,
    'description' : IDL.Text,
    'location' : IDL.Text,
  });
  const Task = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'isCompleted' : IDL.Bool,
    'dueDate' : IDL.Int,
    'priority' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Email = IDL.Record({
    'id' : IDL.Text,
    'subject' : IDL.Text,
    'isStarred' : IDL.Bool,
    'body' : IDL.Text,
    'isRead' : IDL.Bool,
    'timestamp' : IDL.Int,
    'senderName' : IDL.Text,
    'category' : IDL.Text,
    'senderEmail' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createEvent' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Int, IDL.Int, IDL.Text],
        [CalendarEvent],
        [],
      ),
    'createTask' : IDL.Func([IDL.Text, IDL.Int, IDL.Text], [Task], []),
    'deleteEvent' : IDL.Func([IDL.Text], [], []),
    'deleteTask' : IDL.Func([IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEmailById' : IDL.Func([IDL.Text], [IDL.Opt(Email)], ['query']),
    'getEmails' : IDL.Func([], [IDL.Vec(Email)], ['query']),
    'getEvents' : IDL.Func([], [IDL.Vec(CalendarEvent)], ['query']),
    'getTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initDemoData' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markEmailRead' : IDL.Func([IDL.Text], [], []),
    'rewriteBody' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'summarizeEmail' : IDL.Func([IDL.Text], [IDL.Text], []),
    'toggleStarEmail' : IDL.Func([IDL.Text], [], []),
    'toggleTask' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };